# -*- coding: utf-8 -*-
"""
Canonical model/storage identifier dictionaries for Galaxy & iPhone smartphones
released through October 2025.  Synonyms are pre-normalised (lower-case,
no whitespace/punctuation) so they align with the `title_normalization` field.
"""

MODEL_SYNONYMS = {
    # ------------------------------------------------------------------
    # Galaxy S Series (S25 ~ S7, including FE variants)
    # ------------------------------------------------------------------
    "galaxy_s25_ultra": [
        "갤럭시s25울트라",
        "galaxys25ultra",
        "galaxys25u",
        "갤럭시s25u",
        "갤s25울트라",
        "갤s25u",
        "s25울트라",
        "s25ultra",
        "s25u",
    ],
    "galaxy_s25_edge": [
        "갤럭시s25엣지",
        "galaxys25edge",
        "galaxys25e",
        "갤럭시s25e",
        "갤s25엣지",
        "갤s25edge",
        "s25엣지",
        "s25edge",
        "s25e",
    ],
    "galaxy_s25_plus": [
        "갤럭시s25플러스",
        "갤럭시s25plus",
        "galaxys25plus",
        "galaxys25p",
        "갤럭시s25p",
        "갤s25플러스",
        "갤s25plus",
        "s25플러스",
        "s25plus",
        "s25p",
    ],
    "galaxy_s25": [
        "갤럭시s25",
        "galaxys25",
        "갤s25",
        "s25",
    ],
    "galaxy_s25_fe": [
        "갤럭시s25fe",
        "galaxys25fe",
        "갤s25fe",
        "s25fe",
    ],
    "galaxy_s24_ultra": [
        "갤럭시s24울트라",
        "galaxys24ultra",
        "galaxys24u",
        "갤럭시s24u",
        "갤s24울트라",
        "갤s24u",
        "s24울트라",
        "s24ultra",
        "s24u",
    ],
    "galaxy_s24_plus": [
        "갤럭시s24플러스",
        "갤럭시s24plus",
        "galaxys24plus",
        "galaxys24p",
        "갤럭시s24p",
        "갤s24플러스",
        "갤s24plus",
        "s24플러스",
        "s24plus",
        "s24p",
    ],
    "galaxy_s24": [
        "갤럭시s24",
        "galaxys24",
        "갤s24",
        "s24",
    ],
    "galaxy_s24_fe": [
        "갤럭시s24fe",
        "galaxys24fe",
        "갤s24fe",
        "s24fe",
    ],
    "galaxy_s23_ultra": [
        "갤럭시s23울트라",
        "galaxys23ultra",
        "galaxys23u",
        "갤럭시s23u",
        "갤s23울트라",
        "갤s23u",
        "s23울트라",
        "s23ultra",
        "s23u",
    ],
    "galaxy_s23_plus": [
        "갤럭시s23플러스",
        "갤럭시s23plus",
        "galaxys23plus",
        "galaxys23p",
        "갤럭시s23p",
        "갤s23플러스",
        "갤s23plus",
        "s23플러스",
        "s23plus",
        "s23p",
    ],
    "galaxy_s23": [
        "갤럭시s23",
        "galaxys23",
        "갤s23",
        "s23",
    ],
    "galaxy_s23_fe": [
        "갤럭시s23fe",
        "galaxys23fe",
        "갤s23fe",
        "s23fe",
    ],
    "galaxy_s22_ultra": [
        "갤럭시s22울트라",
        "galaxys22ultra",
        "galaxys22u",
        "갤럭시s22u",
        "갤s22울트라",
        "갤s22u",
        "s22울트라",
        "s22ultra",
        "s22u",
    ],
    "galaxy_s22_plus": [
        "갤럭시s22플러스",
        "갤럭시s22plus",
        "galaxys22plus",
        "galaxys22p",
        "갤럭시s22p",
        "갤s22플러스",
        "갤s22plus",
        "s22플러스",
        "s22plus",
        "s22p",
    ],
    "galaxy_s22": [
        "갤럭시s22",
        "galaxys22",
        "갤s22",
        "s22",
    ],
    "galaxy_s21_ultra": [
        "갤럭시s21울트라",
        "galaxys21ultra",
        "galaxys21u",
        "갤럭시s21u",
        "갤s21울트라",
        "갤s21u",
        "s21울트라",
        "s21ultra",
        "s21u",
    ],
    "galaxy_s21_plus": [
        "갤럭시s21플러스",
        "갤럭시s21plus",
        "galaxys21plus",
        "galaxys21p",
        "갤럭시s21p",
        "갤s21플러스",
        "갤s21plus",
        "s21플러스",
        "s21plus",
        "s21p",
    ],
    "galaxy_s21": [
        "갤럭시s21",
        "galaxys21",
        "갤s21",
        "s21",
    ],
    "galaxy_s21_fe": [
        "갤럭시s21fe",
        "galaxys21fe",
        "갤s21fe",
        "s21fe",
    ],
    "galaxy_s20_ultra": [
        "갤럭시s20울트라",
        "galaxys20ultra",
        "galaxys20u",
        "갤럭시s20u",
        "갤s20울트라",
        "갤s20u",
        "s20울트라",
        "s20ultra",
        "s20u",
    ],
    "galaxy_s20_plus": [
        "갤럭시s20플러스",
        "갤럭시s20plus",
        "galaxys20plus",
        "galaxys20p",
        "갤럭시s20p",
        "갤s20플러스",
        "갤s20plus",
        "s20플러스",
        "s20plus",
        "s20p",
    ],
    "galaxy_s20": [
        "갤럭시s20",
        "galaxys20",
        "갤s20",
        "s20",
    ],
    "galaxy_s20_fe": [
        "갤럭시s20fe",
        "galaxys20fe",
        "갤s20fe",
        "s20fe",
    ],
    "galaxy_s10_5g": [
        "갤럭시s105g",
        "galaxys105g",
        "갤s105g",
        "s105g",
    ],
    "galaxy_s10_plus": [
        "갤럭시s10플러스",
        "갤럭시s10plus",
        "galaxys10plus",
        "galaxys10p",
        "갤럭시s10p",
        "갤s10플러스",
        "갤s10plus",
        "s10플러스",
        "s10plus",
        "s10p",
    ],
    "galaxy_s10": [
        "갤럭시s10",
        "galaxys10",
        "갤s10",
        "s10",
    ],
    "galaxy_s10e": [
        "갤럭시s10e",
        "galaxys10e",
        "갤s10e",
        "s10e",
    ],
    "galaxy_s9_plus": [
        "갤럭시s9플러스",
        "갤럭시s9plus",
        "galaxys9plus",
        "galaxys9p",
        "갤럭시s9p",
        "갤s9플러스",
        "갤s9plus",
        "s9플러스",
        "s9plus",
        "s9p",
    ],
    "galaxy_s9": [
        "갤럭시s9",
        "galaxys9",
        "갤s9",
        "s9",
    ],
    "galaxy_s8_plus": [
        "갤럭시s8플러스",
        "갤럭시s8plus",
        "galaxys8plus",
        "galaxys8p",
        "갤럭시s8p",
        "갤s8플러스",
        "갤s8plus",
        "s8플러스",
        "s8plus",
        "s8p",
    ],
    "galaxy_s8": [
        "갤럭시s8",
        "galaxys8",
        "갤s8",
        "s8",
    ],
    "galaxy_s7_edge": [
        "갤럭시s7엣지",
        "galaxys7edge",
        "갤s7엣지",
        "s7엣지",
        "s7edge",
    ],
    "galaxy_s7": [
        "갤럭시s7",
        "galaxys7",
        "갤s7",
        "s7",
    ],
    # ------------------------------------------------------------------
    # Galaxy Note Series
    # ------------------------------------------------------------------
    "galaxy_note20_ultra": [
        "갤럭시노트20울트라",
        "galaxynote20ultra",
        "note20울트라",
        "note20ultra",
        "노트20울트라",
        "노트20u",
    ],
    "galaxy_note20": [
        "갤럭시노트20",
        "galaxynote20",
        "note20",
        "노트20",
    ],
    "galaxy_note10_plus": [
        "갤럭시노트10플러스",
        "galaxynote10plus",
        "note10플러스",
        "note10plus",
        "노트10플러스",
        "노트10plus",
    ],
    "galaxy_note10": [
        "갤럭시노트10",
        "galaxynote10",
        "note10",
        "노트10",
    ],
    "galaxy_note9": [
        "갤럭시노트9",
        "galaxynote9",
        "note9",
        "노트9",
    ],
    "galaxy_note8": [
        "갤럭시노트8",
        "galaxynote8",
        "note8",
        "노트8",
    ],
    # ------------------------------------------------------------------
    # Galaxy Z Series (Fold/Flip)
    # ------------------------------------------------------------------
    "galaxy_z_fold7": [
        "갤럭시z폴드7",
        "galaxyzfold7",
        "z폴드7",
        "zfold7",
        "폴드7",
    ],
    "galaxy_z_flip7": [
        "갤럭시z플립7",
        "galaxyzflip7",
        "z플립7",
        "zflip7",
        "플립7",
    ],
    "galaxy_z_flip7_fe": [
        "갤럭시z플립7fe",
        "galaxyzflip7fe",
        "z플립7fe",
        "zflip7fe",
        "플립7fe",
    ],
    "galaxy_z_fold6": [
        "갤럭시z폴드6",
        "galaxyzfold6",
        "z폴드6",
        "zfold6",
        "폴드6",
    ],
    "galaxy_z_flip6": [
        "갤럭시z플립6",
        "galaxyzflip6",
        "z플립6",
        "zflip6",
        "플립6",
    ],
    "galaxy_z_fold5": [
        "갤럭시z폴드5",
        "galaxyzfold5",
        "z폴드5",
        "zfold5",
        "폴드5",
    ],
    "galaxy_z_flip5": [
        "갤럭시z플립5",
        "galaxyzflip5",
        "z플립5",
        "zflip5",
        "플립5",
    ],
    "galaxy_z_fold4": [
        "갤럭시z폴드4",
        "galaxyzfold4",
        "z폴드4",
        "zfold4",
        "폴드4",
    ],
    "galaxy_z_flip4": [
        "갤럭시z플립4",
        "galaxyzflip4",
        "z플립4",
        "zflip4",
        "플립4",
    ],
    "galaxy_z_fold3": [
        "갤럭시z폴드3",
        "galaxyzfold3",
        "z폴드3",
        "zfold3",
        "폴드3",
    ],
    "galaxy_z_flip3": [
        "갤럭시z플립3",
        "galaxyzflip3",
        "z플립3",
        "zflip3",
        "플립3",
    ],
    "galaxy_z_fold2": [
        "갤럭시z폴드2",
        "galaxyzfold2",
        "z폴드2",
        "zfold2",
        "폴드2",
    ],
    "galaxy_z_flip": [
        "갤럭시z플립",
        "galaxyzflip",
        "z플립",
        "zflip",
        "플립",
    ],
    # ------------------------------------------------------------------
    # iPhone Series (17 ~ 7, XS/XR line, SE)
    # ------------------------------------------------------------------
    "iphone_17_pro_max": [
        "아이폰17프로맥스",
        "iphone17promax",
        "17프로맥스",
        "17promax",
        "아이폰17pm",
        "iphone17pm",
    ],
    "iphone_17_pro": [
        "아이폰17프로",
        "iphone17pro",
        "17프로",
        "17pro",
    ],
    "iphone_17_plus": [
        "아이폰17플러스",
        "iphone17plus",
        "17플러스",
        "17plus",
        "아이폰17플",
        "iphone17p",
    ],
    "iphone_17": [
        "아이폰17",
        "iphone17",
    ],
    "iphone_16_pro_max": [
        "아이폰16프로맥스",
        "iphone16promax",
        "16프로맥스",
        "16promax",
        "아이폰16pm",
        "iphone16pm",
    ],
    "iphone_16_pro": [
        "아이폰16프로",
        "iphone16pro",
        "16프로",
        "16pro",
    ],
    "iphone_16_plus": [
        "아이폰16플러스",
        "iphone16plus",
        "16플러스",
        "16plus",
        "아이폰16플",
        "iphone16p",
    ],
    "iphone_16": [
        "아이폰16",
        "iphone16",
    ],
    "iphone_16e": [
        "아이폰16e",
        "iphone16e",
        "16e",
    ],
    "iphone_15_pro_max": [
        "아이폰15프로맥스",
        "iphone15promax",
        "15프로맥스",
        "15promax",
        "아이폰15pm",
        "iphone15pm",
    ],
    "iphone_15_pro": [
        "아이폰15프로",
        "iphone15pro",
        "15프로",
        "15pro",
    ],
    "iphone_15_plus": [
        "아이폰15플러스",
        "iphone15plus",
        "15플러스",
        "15plus",
        "아이폰15플",
        "iphone15p",
    ],
    "iphone_15": [
        "아이폰15",
        "iphone15",
    ],
    "iphone_14_pro_max": [
        "아이폰14프로맥스",
        "iphone14promax",
        "14프로맥스",
        "14promax",
        "아이폰14pm",
        "iphone14pm",
    ],
    "iphone_14_pro": [
        "아이폰14프로",
        "iphone14pro",
        "14프로",
        "14pro",
    ],
    "iphone_14_plus": [
        "아이폰14플러스",
        "iphone14plus",
        "14플러스",
        "14plus",
        "아이폰14플",
        "iphone14p",
    ],
    "iphone_14": [
        "아이폰14",
        "iphone14",
    ],
    "iphone_13_pro_max": [
        "아이폰13프로맥스",
        "iphone13promax",
        "13프로맥스",
        "13promax",
        "아이폰13pm",
        "iphone13pm",
    ],
    "iphone_13_pro": [
        "아이폰13프로",
        "iphone13pro",
        "13프로",
        "13pro",
    ],
    "iphone_13_mini": [
        "아이폰13미니",
        "iphone13mini",
        "13미니",
        "13mini",
    ],
    "iphone_13": [
        "아이폰13",
        "iphone13",
    ],
    "iphone_12_pro_max": [
        "아이폰12프로맥스",
        "iphone12promax",
        "12프로맥스",
        "12promax",
        "아이폰12pm",
        "iphone12pm",
    ],
    "iphone_12_pro": [
        "아이폰12프로",
        "iphone12pro",
        "12프로",
        "12pro",
    ],
    "iphone_12_mini": [
        "아이폰12미니",
        "iphone12mini",
        "12미니",
        "12mini",
    ],
    "iphone_12": [
        "아이폰12",
        "iphone12",
    ],
    "iphone_11_pro_max": [
        "아이폰11프로맥스",
        "iphone11promax",
        "11프로맥스",
        "11promax",
        "아이폰11pm",
        "iphone11pm",
    ],
    "iphone_11_pro": [
        "아이폰11프로",
        "iphone11pro",
        "11프로",
        "11pro",
    ],
    "iphone_11": [
        "아이폰11",
        "iphone11",
    ],
    "iphone_xs_max": [
        "아이폰xs맥스",
        "iphonexsmax",
        "xs맥스",
        "xsmax",
    ],
    "iphone_xs": [
        "아이폰xs",
        "iphonexs",
    ],
    "iphone_xr": [
        "아이폰xr",
        "iphonexr",
    ],
    "iphone_x": [
        "아이폰x",
        "iphonex",
    ],
    "iphone_8_plus": [
        "아이폰8플러스",
        "iphone8plus",
        "아이폰8플",
        "iphone8p",
    ],
    "iphone_8": [
        "아이폰8",
        "iphone8",
    ],
    "iphone_7_plus": [
        "아이폰7플러스",
        "iphone7plus",
        "아이폰7플",
        "iphone7p",
    ],
    "iphone_7": [
        "아이폰7",
        "iphone7",
    ],
    "iphone_se_3": [
        "아이폰se3",
        "iphonese3",
        "se3",
        "아이폰se2022",
        "iphone2022se",
    ],
    "iphone_se_2": [
        "아이폰se2",
        "iphonese2",
        "se2",
        "아이폰se2020",
        "iphone2020se",
    ],
}

STORAGE_SYNONYMS = {
    "1tb": ["1tb", "1테라", "1테라바이트", "1t", "1000gb"],
    "512g": ["512g", "512기가", "512gb", "0.5tb", "512gig"],
    "256g": ["256g", "256기가", "256gb", "256gig"],
    "128g": ["128g", "128기가", "128gb", "128gig"],
    "64g": ["64g", "64기가", "64gb", "64gig"],
    "32g": ["32g", "32기가", "32gb", "32gig"],
}


def sorted_model_keys_desc():
    """Return canonical model keys sorted by descending length for priority matching."""
    return sorted(MODEL_SYNONYMS.keys(), key=len, reverse=True)
